---
resources:
- name: attendee-service
  type: git
  source:
    uri: https://github.com/goehringc/pcf-attendee-service-code
    branch: master

- name: deploy-attendee-service
  type: cf
  source:
    api: {{cf-api-aws}}
    username: {{cf-user-aws}} 
    password: {{cf-pwd-aws}}
    organization: {{cf-org-aws}}
    space: {{cf-space-aws}}
    skip_cert_check: true
jobs:
- name: build 
  public: true
  plan:
  - get: attendee-service
  - task: package
    file: attendee-service/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service/manifest.yml
      path: package-output/attendee-service.jar

